launch-yocto.sh: add limit to cyclictest
seapath/ci pull request #90
Opened 2024-07-08 12:12 UTC by bchedotel

2024-07-08 15:33 UTC, dupremathieu submitted a review, later dismissed

2024-07-10 07:44 UTC, dupremathieu requested changes
Add a commit description.

2024-07-10 07:53 UTC, eroussy requested changes

2024-07-10 07:53 UTC, eroussy commented on openlab/test-report.adoc
> +include::include/cyclictest_vm.adoc[]
Put this one in optional : 
`include::include/cyclictest_vm.adoc[opts=optional]`

If the CI fails during the test of the hypervisor this file will not be created, but we to create the report.

2024-07-10 14:30 UTC, eroussy requested changes

2024-07-10 14:30 UTC, eroussy commented on launch-yocto.sh
> +  "${WORK_DIR}/ci/latency-tests-analysis/cyclictest-analysis/gen_cyclic_test.sh" \
can you make that run in a cqfd ?
You can use the cqfd already contained in the openlab directory.

2024-07-11 11:59 UTC, eroussy approved these changes

2024-07-11 12:00 UTC, dupremathieu approved these changes

2024-07-11 12:00 UTC, merged